version: '2'
services:
  nginx:
    container_name: nginx
    build: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    links:
      - gitlab
      - jenkins
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab
    restart: always
    hostname: 'git.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://git.example.com'
        # Add any other gitlab.rb configuration here, each on its own line
    volumes:
      - '/data/gitlab/config:/etc/gitlab'
      - '/data/gitlab/logs:/var/log/gitlab'
      - '/data/gitlab/data:/var/opt/gitlab'
  jenkins:
    #image: 'jenkins/jenkins:lts'
    image: 'reg.example.com/jenkins:lts'
    container_name: jenkins
    restart: always
    volumes:
      - '/data/jenkins_home:/var/jenkins_home'
  reg:
    image: 'registry:2'
    container_name: reg
    restart: always
    volumes:
      - '/data/registry:/var/lib/registry'
