version: '2'
services:
  jenkins:
    #image: 'jenkins/jenkins:lts'
    image: 'reg.example.com/jenkins:lts'
    container_name: jenkins
    restart: always
    volumes:
      - /data/jenkins_home:/var/jenkins_home
      - /var/run:/var/run:rw
      - /usr/bin/docker:/usr/bin/docker
